apiVersion: v1
kind: Service
metadata:
  name: loopii-service
spec:
  type: NodePort
  selector:
    app: myapp
    tier: frontend
  ports:
    - port: 80
      targetPort: 3040
      nodePort: 30080
